// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsjthJPLh-3T8DjXECKTZPSsHDglkV72g',
    appId: '1:446526176458:web:92516f496d74114c4f0833',
    messagingSenderId: '446526176458',
    projectId: 'internship-task-3a303',
    authDomain: 'internship-task-3a303.firebaseapp.com',
    storageBucket: 'internship-task-3a303.firebasestorage.app',
    measurementId: 'G-V3PMVQ112K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBon8lSFBfLMm0k1OVNFsTWC4QGx5XO-oY',
    appId: '1:446526176458:android:90ff8c64ff91aa354f0833',
    messagingSenderId: '446526176458',
    projectId: 'internship-task-3a303',
    storageBucket: 'internship-task-3a303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaO4Bz4ULZ5r8S_6RwydjE3IaQ3ISWpDk',
    appId: '1:446526176458:ios:be0cbf428cf703364f0833',
    messagingSenderId: '446526176458',
    projectId: 'internship-task-3a303',
    storageBucket: 'internship-task-3a303.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaO4Bz4ULZ5r8S_6RwydjE3IaQ3ISWpDk',
    appId: '1:446526176458:ios:be0cbf428cf703364f0833',
    messagingSenderId: '446526176458',
    projectId: 'internship-task-3a303',
    storageBucket: 'internship-task-3a303.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsjthJPLh-3T8DjXECKTZPSsHDglkV72g',
    appId: '1:446526176458:web:62390ba7251d8b684f0833',
    messagingSenderId: '446526176458',
    projectId: 'internship-task-3a303',
    authDomain: 'internship-task-3a303.firebaseapp.com',
    storageBucket: 'internship-task-3a303.firebasestorage.app',
    measurementId: 'G-JPHM9S1L7C',
  );
}